### ISSUE TITLE
Examples with use case

### ISSUE THREAD

**Issue by prakash-indorkar** [jdgamble555/adv-firestore-functions#10]
Hi, first of all, I would say your contribution is remarkable. Thank you for giving your knowledge and code for free to use. 

The examples in readme are good to know what features are available. It would be really useful if can be presented on a use case or scenario-based example.
What I mean is maybe, considering some kind of example having cloud database collection and documents with example values. And then using your package functions, how things can be simplified, would definitely make it easy to understand. Sometimes it's difficult to understand the flow to use it in the correct way. Hope I make sense.

Thanks anyway. Regards, Prakash

**Comment by jdgamble555** [comment]
@prakash-indorkar It takes time to write these examples :(  I am trying to write them on my website here and there https://fireblog.io.   Is there any particular function you are trying to get a handle on?

**Comment by prakash-indorkar** [comment]
Hi Thanks for your quick reply. 

ok, What I'm looking for a solution is .. as below my database structure

Users ( uid, displayName, email, displayImage, address, myPosting )

Postings ( id, title, description, category, isConsumed, isDeleted, bestBeforeDate, postedBy )

I wanted a count for total users and total posting which I can get using _counters collection. that's brilliant.

Now how to get count for how many are isConsumed, and isDeleted, and then notice I have bestDeforeDate (it's for food category), there are categories for item like ( food, books, toys etc).

so in my front end I want to show users count of  
- Total_users, 
- Total_postings ( overall ), 
- Total_consumed , 
- and Total_active

Total active =  (total_posting - (total consumed - total deleted)),

but notice I have a bestbefore date. means this a posting that was active but after the passing date can be expired. once expired it can not be consumed, but the user can delete it (flag deleted). So my active count should go down, whenever posting expires. 

one possible solution is .. to have is_expired flag .. and run a corn job every day to check for bestBeforeDate and flag it as expired and decrease the count of active. Or you can suggest to me a better solution, please.

So how to achieve this with your package? 

Thanks once again for your attention. Regards

**Comment by jdgamble555** [comment]
- total_users - (_counters/users)
- total_postings (_counters/postings)

I did not write a way to counter the number of documents that get deleted.  I think that is such a specific case for you.  

Query Counters can count items that exist.  You could easily count the number of postings of a user by doing:

```typescript
import { eventExists, queryCounter, getValue } from 'adv-firestore-functions';

// assumes there is a userId (that does not change) on a 'posting' doc or userRef

functions.firestore
    .document('postings/{docId}')
    .onWrite(async (change: any, context: any) => {

        // get userId from Doc
        const userId = getValue(change, 'userId');
         // get user doc reference
        const userRef = db.doc(`users/${userId}`);  
        // get query for postings by that user
        const postsQuery = db.collection('postings').where('userDoc', "==", userRef);

        // auto update postingsCount on usersDoc
        await queryCounter(change, context, postsQuery, userRef);

       return null;
    });
```

And on your user doc, you will have the value ```postingsCount``` which will automatically total the number of postings made by each user.

- You could write your own program for **total deleted** by checking the `onDelete()` trigger in Firebase Functions.  

```typescript
functions.firestore
    .document('postings/{docId}')
    .onDelete(async (change: any, context: any) => {

         // assuming "deletedCount exists, otherwise you could write code to initialize it to 0

        const postingsRef = db.doc(`_counters/postings`);  

        // update count 
        const i = firebase.firestore.FieldValue.increment(1);

        // Update read count 
        await postingsRef.update({ deletedCount: i });

        return null;

});
```
And you will have **_counters/postings/deletedCount = someNumber**



- The **isConsumed** I am assuming just changes manually.  You could write something like this:

```typescript
functions.firestore
    .document('postings/{docId}')
    .onWrite(async (change: any, context: any) => {

    // if isConsumed gets changed
    if (valueChange(change, 'isConsumed')) {
        // you could add some code here to check that
       //  "_counters/postings/isConsumed exists, otherwise sets to 0
        // if isConsumed = true - increment, false decrement
       const n = getValue(change, 'isConsumed) ? 1 : -1;
       const i = firebase.firestore.FieldValue.increment(n);
       const countRef = db.doc(`_counters/postings`);  
       await countRef.update({ consumedCount: i});
  }
return null;
});

```  

All of this is untested, but should work.

And on the front end to get **Total active**:

total_postings = **_counters/postings/count** 
total_consumed = **_counters/postings/consumedCount**
total_deleted = **_counters/postings/deletedCount**

(total_posting - (total consumed - total deleted))

There is a lot of stuff missing here, but this should get you started.  I do see a use case for counting changes for certain items, which I may add later... this is basic, but I may simplify some of this in the code later.

Hope this helps,
J

**Comment by prakash-indorkar** [comment]
Excellent!.. this is useful.  isDeleted is similar to isConsumed (manually set by a user - just a flag. Records will be always there in database). So applied similar logic as isConsumed. 

Only bit left to solve is bestBeforeDate (expiry trigger), which I think I'll do it with pubsub schedule.

What I'll do is I'll write the whole function as per my need and post it again so that you can validate it. It may help others too.

Thank you so much. Hope to see more examples on your blog.

**Comment by prakash-indorkar** [comment]
ok here is my magicFunction. I have few questions though

1. If I run all the task in one function would there be any issue?
2. With updateJoinData, getJoinData,  how to make sure they would not run on every change? I am bit confused between createJoinData, and getJoinData.
3. I'm using  if (!change.before.data && change.after.data) to make sure if the event is onCreate().. is this correct or not required?
4. what is the use of undefind in  - await tagIndex(change, context, 'tags', '_tags', undefined, 'tAggregate');
5. I have changed your logic a bit  
 `const n = getValue(change, 'isConsumed') ? 1 : -1;` 
because I'm only allowing to set it consumed once consumed or deleted users can not change it back. So 
 `const n = getValue(change, 'isConsumed') ? 1 : 0;`    - is this correct?


For category indexing, I'm waiting for any example. In my case category is single value.
Also I have tags, but right now not so confident to use it.

for active sharings I have created another counter  "activeCount" which will update with other couters .. so no need to calulate
as with my login in front-end .. a sharing can be deleted if not consumed or expired, Also a sharing can be expired and deleted later, so depending on this I have set activeRecords count.

I have implement isExpiry cronJob and its working as expected. 

```javascript
import { eventExists, queryCounter, getValue, colCounter, isTriggerFunction, triggerFunction, updateJoinData, getJoinData } from 'adv-firestore-functions';

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

const db = admin.firestore();


exports.magicFunction = functions.firestore.document('/{colId}/{docId}')
    .onWrite(async (change, context) => {
        const colId = context.params.colId;

        // don't run if repeated function
        if (await eventExists(context) || colId.startsWith('_') || isTriggerFunction(change, context)) {
            return null;
        }

        const promises = [];

        try {
            //this will update/create counter "_counters/colId
            promises.push(colCounter(change, context));

            //this will add/update createdAt and updatedAt
            promises.push(triggerFunction(change));

            if (colId === 'sharings') {
                const countRef = db.doc(`_counters/sharings`);

                // new record
                if (!change.before.data && change.after.data) {
                    promises.push(countRef.update({
                        activeCount: admin.firestore.FieldValue.increment(1)
                    }));

                    const joinFields = ['displayName', 'photoURL'];
                    const userId = getValue(change, 'userId');
                    const userRef = db.collection(`users/${userId}`);
                    promises.push(getJoinData(change, userRef, joinFields, 'user'));
                }

                // if isConsumed gets changed
                if (valueChange(change, 'isConsumed')) {
                    const n = getValue(change, 'isConsumed') ? 1 : 0;
                    if (n > 0) {
                        promises.push(countRef.update({
                            consumedCount: admin.firestore.FieldValue.increment(1),
                            activeCount: admin.firestore.FieldValue.increment(-1)
                        }));
                    }
                }

                // if isDeleted gets changed  (also check if isExpired true then decrease activeCount)
                if (valueChange(change, 'isDeleted')) {
                    const d = getValue(change, 'isDeleted') ? 1 : 0;
                    const e = getValue(change, 'isExpired') ? 1 : 0;

                    if (d > 0 && e == 0) {
                        promises.push(countRef.update({
                            deletedCount: admin.firestore.FieldValue.increment(1),
                            activeCount: admin.firestore.FieldValue.increment(-1)
                        }));
                    } else if (d > 0 && e > 0) {
                        promises.push(countRef.update({
                            deletedCount: admin.firestore.FieldValue.increment(1)
                        }));
                    }
                }

                // if isExpired gets changed
                if (valueChange(change, 'isExpired')) {
                    const e = getValue(change, 'isExpired') ? 1 : 0;

                    if (e > 0) {
                        promises.push(countRef.update({
                            expiredCount: admin.firestore.FieldValue.increment(1),
                            activeCount: admin.firestore.FieldValue.increment(-1)
                        }));
                    }
                }
            }

            if (colId === 'users') {
                const docId = context.params.docId;
                const queryRef = db.collection('sharings').where('userId', '==', docId)
                const joinFields = ['displayName', 'photoURL'];
                promises.push(updateJoinData(change, queryRef, joinFields, 'user'));
            }

            // Execute all jobs concurrently
            await Promise.all(promises);

        } catch (e) {
            console.log('Magic function error: ' + e);
        }
        return null;
    });

exports.setExpiryCronjob = functions.pubsub.schedule('30 23 * * *')
    .timeZone('Australia/Perth')
    .onRun(async context => {

        // Consistent timestamp
        const now = admin.firestore.Timestamp.now();

        // fetch all sharings tobe set expired
        const query = db.collection('sharings')
            .where('bestBeforeDate', '<=', now)
            .where('isConsumed', '==', false)
            .where('isDeleted', '==', false)
            .where('isExpired', '==', false);

        const tasks = await query.get();


        // Jobs to execute concurrently. // array of promises
        const jobs = [];

        // Loop over documents and push job.

        tasks.forEach(snapshot => {
            // Job is to update isExpired to true
            const job = snapshot.ref.update({ isExpired: true })
                .catch((err) => console.log(`Error occured during setExpiry cron job for Sharing id: ${snapshot.data().id}: ` + err));
            //push each promise to array
            jobs.push(job);
        });

        // Execute all jobs concurrently
        await Promise.all(jobs);
        return null;
    });
```

**Comment by jdgamble555** [comment]
1.) There are different styles to how you group functions.  I would, however, only recommend a universal function when you want to run something most of the time.  There are several reasons for this:
- The function runs every single change.  View your logs and you will see this is a LOT.  This costs money.
- The events (to prevent multiple instances of the same function) costs money to write to the database.
- Larger functions are more prone to error.  One error, for example, would mess up other features in the function.

My suggestion would be:

- A universal **counter** function.... never edit this, and it will always stay up-to-date in larger databases.  VERY IMPORTANT!  If you had an error while debugging your other functionalities, your counts would be off.  Keep this separate!
- A function for each collection **onWrite** (users, posts, etc).  This keeps everything organized, and easy to read.
- **Cron Jobs** - have to be separate anyway

2.) **getJoinData** is actually inside **createJoinData**... it is useful when you want to change data before it is updated.  For example:
- **createJoinData** automatically adds the **user** info on a **post** doc during the creation of a **post** doc.  
- **getJoinData** will just get the **user** info, you can manually change it, and use a **triggerfunction** to automatically add it to the **post** doc

3.) on an **onWrite** function, simply:
```typescript
import { createDoc } from 'adv-firestore-functions';

if (createDoc(change)) {
    // a document is being created, so do something...
}
```
4.) Passing **undefined** to a function in typescript keeps the default value of the function (as said at the bottom of my readme).  You have to have commas to denote the parameter.  This is just how typescript works, and here allows you to avoid changing default values.  In this case it defaults to **true**, which creates an **_all** doc with all the tags in one place (to save money on multiple document reads)
5.)  Assuming **isConsumed** is true, and you want to count the number of **true** values... yes.  I am going to write an update tonight for **queryCounter** so you don't have to do that... I will let you know when it is finished. (See next post---when I write it-- for updated answer to this)

So a few things here.  
1.) You have way too much code in one function.  This is horrible mainly for testing and money purposes.  **Test one feature at a time!**  
2.) You could avoid the cron job by have an **expired** field on your docs.  Then search on the front end for expired by dates that are not past the current date [stackoverflow](https://stackoverflow.com/a/47005940/271450)
3.) I would run the **triggerFunction** to updated the dates LAST.  You always only want ONE trigger function to avoid extraneous costs.  This makes sure everything works correctly.

**Comment by jdgamble555** [comment]
Alright, done.  I created **conditionQuery** so that you can easily count your changes. see [here](https://github.com/jdgamble555/adv-firestore-functions)

Examples:

```typescript
// Automatically update isConsumedCount, isDeletedCount, isExpiredCount
await conditionCounter(change, context, 'isConsumed', '==', true);
await conditionCounter(change, context, 'isDeleted', '==', true);
await conditionCounter(change, context, 'isExpired', '==', true);

// get count info
const countRef = db.doc('_counters/postings');
const countSnap = await countRef.get();

// update total count iff other promises have completed
// whatever your formula may be...
const totalActive = countSnap.get(count) - countSnap.get(isDeletedCount) - countSnap.get(isExpiredCount);
await countRef.set({ totalActive }, { merge: true });
```

Let me know if everything works, and I will close this issue.

**Note:**  I should add while my code is much shorter and easier, technically you're going to incur more reads and writes than a custom function.  For example: you update **isConsumedCount**, **isDeletedCount**, **isExpiredCount** at different times incurring 3 reads and writes separately, when you could incur one read, calculate everything, and one write by updating them in your own custom function at once.  If your app is not large, or is not using data every few seconds, this may not be a big deal.  It just depends. I will be the first to admit that that function would get complicated with increments, but you're probably not going to update all 3 at the same time anyway, making this a moot point... just depends on your program.

**Comment by prakash-indorkar** [comment]
Hi.. Thank you for another brilliant function. I haven't used it though would give it a try later today. And as per your recommendation, I have seprated all the functions.
Thank you once again.

**Comment by prakash-indorkar** [comment]
Hi . there, I dont know if I'm in trubble or not .. I had to delete my app and project.  and later had to chat with support team to check the project has been deleted or not and not running any function on server. I still don't know what would be my billing like tomorrow.

below is my code .. could you please tell me what went wrong (I'm using javascript only)

Also, I must tell you it created _events collection instead of _counters..   the triggerFunction(change) worked with no issue when I updated a record. When I changed a data in user table .. it started running a function .. and went onto infinite loop creating multiple documents..   I do not know how to stop that running function if it happens again. I deleted the app and whole project later..  It was just upder developement project so not worries about the data. 



```javascript

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);
const adv_fsf = require('adv-firestore-functions');
const db = admin.firestore();
const settings = { timestampInSnapshots: true };
db.settings(settings)


exports.createCollectionCounter = functions.firestore.document('/{colId}/{docId}')
    .onWrite(async (change, context) => {
        const colId = context.params.colId;

        // don't run if repeated function
        if (await adv_fsf.eventExists(context) || colId.startsWith('_') || adv_fsf.isTriggerFunction(change, context)) {
            return null;
        }
        try {
            //this will update/create counter "_counters/colId  
            if (colId === 'sharings' || colId === 'users') {
                await adv_fsf.colCounter(change, context);
            }
        } catch (e) {
            console.log('collection count function error: ' + e);
        }
        return null;
    });


exports.autoCreatedAtUpdatedAt = functions.firestore.document('/{colId}/{docId}')
    .onWrite(async (change, context) => {
        const colId = context.params.colId;

        // don't run if repeated function
        if (await adv_fsf.eventExists(context) || adv_fsf.isTriggerFunction(change, context)) {
            return null;
        }
        try {
            if (colId === 'sharings' || colId === 'users' || colId === 'conversations') {
                await adv_fsf.triggerFunction(change);
            }
        } catch (e) {
            console.log('createdAtUpdatedAt function error: ' + e);
        }
        return null;
    });


exports.getUserDataInSharing = functions.firestore.document('/sharings/{docId}')
    .onWrite(async (change, context) => {
        // don't run if repeated function
        if (await adv_fsf.eventExists(context) || adv_fsf.isTriggerFunction(change, context)) {
            return null;
        }
        try {
            const joinFields = ['displayName', 'photoURL'];
            const userId = adv_fsf.getValue(change, 'userId');
            const userRef = db.collection(`users/${userId}`);
            await adv_fsf.createJoinData(change, userRef, joinFields, 'user');
        } catch (e) {
            console.log('Get user data on sharing - function error: ' + e);
        }
        return null;
    });

exports.updateUserDataInSharing = functions.firestore.document('/users/{docId}')
    .onWrite(async (change, context) => {
        // don't run if repeated function
        if (await adv_fsf.eventExists(context) || adv_fsf.isTriggerFunction(change, context)) {
            return null;
        }
        try {
            const docId = context.params.docId;
            const queryRef = db.collection('sharings').where('userId', '==', docId);
            const joinFields = ['displayName', 'photoURL'];
            await adv_fsf.updateJoinData(change, queryRef, joinFields, 'user');
        } catch (e) {
            console.log('Update user data on sharing - function error: ' + e);
        }
        return null;
    });



exports.conditionCounterFunction = functions.firestore.document('/sharings/{docId}')
    .onWrite(async (change, context) => {

        // don't run if repeated function
        if (await adv_fsf.eventExists(context) || adv_fsf.isTriggerFunction(change, context)) {
            return null;
        }

        const promises = [];

        try {

            const countRef = db.doc(`_counters/sharings`);
            // new record
            if (adv_fsf.createDoc(change)) {
                promises.push(countRef.update({
                    activeCount: admin.firestore.FieldValue.increment(1)
                }));

            }

            // if isConsumed gets changed
            if (valueChange(change, 'isConsumed')) {
                const n = getValue(change, 'isConsumed') ? 1 : 0;
                if (n > 0) {
                    promises.push(countRef.update({
                        consumedCount: admin.firestore.FieldValue.increment(1),
                        activeCount: admin.firestore.FieldValue.increment(-1)
                    }));
                }
            }

            // if isDeleted gets changed  (also check if isExpired true then decrease activeCount)
            if (valueChange(change, 'isDeleted')) {
                const deleted = adv_fsf.getValue(change, 'isDeleted') ? true : false;
                const expired = adv_fsf.getValue(change, 'isExpired') ? true : false;

                if (deleted && !expired) {
                    promises.push(countRef.update({
                        deletedCount: admin.firestore.FieldValue.increment(1),
                        activeCount: admin.firestore.FieldValue.increment(-1)
                    }));
                } else if (deleted && expired) {
                    promises.push(countRef.update({
                        deletedCount: admin.firestore.FieldValue.increment(1)
                    }));
                }
            }

            // if isExpired gets changed
            if (adv_fsf.valueChange(change, 'isExpired')) {
                const expired = adv_fsf.getValue(change, 'isExpired') ? 1 : 0;

                if (expired) {
                    promises.push(countRef.update({
                        expiredCount: admin.firestore.FieldValue.increment(1),
                        activeCount: admin.firestore.FieldValue.increment(-1)
                    }));
                }
            }
            // Execute all jobs concurrently
            await Promise.all(promises);

        } catch (e) {
            console.log('condition counter function error: ' + e);
        }
        return null;
    });


exports.setExpiryCronjob = functions.pubsub.schedule('30 23 * * *')
    .timeZone('Australia/Perth')
    .onRun(async context => {

        // Consistent timestamp
        const now = admin.firestore.Timestamp.now();

        // fetch all sharings tobe set expired
        const query = db.collection('sharings')
            .where('bestBeforeDate', '<=', now)
            .where('isConsumed', '==', false)
            .where('isDeleted', '==', false)
            .where('isExpired', '==', false);

        const tasks = await query.get();

        // Jobs to execute concurrently. // array of promises
        const jobs = [];

        // Loop over documents and push job.

        tasks.forEach(snapshot => {
            // Job is to update isExpired to true
            const job = snapshot.ref.update({ isExpired: true })
                .catch((err) => console.log(`Error occured during setExpiry cron job for Sharing id: ${snapshot.data().id}: ` + err));
            //push each promise to array
            jobs.push(job);
        });

        // Execute all jobs concurrently
        await Promise.all(jobs);
        return null;
    });


```

**Comment by jdgamble555** [comment]
1.) **Test only 1 Function at a time!**  How are you even going to know which function is causing the loop!?  Always test one function at a time.  You can go to the firebase console -> Functions -> click the bar on the right next to the function, and view logs...  If it is an infinite loop, the logs will show this.  I purposely wrote my functions to log everything.  **DELETE THE FUNCTION IMMEDIATLEY**!  You can do this in the function console!

2.) ```const adv_fsf = require('adv-firestore-functions');```  Do not import the package this way.  Please follow my instructions.  Only import the functions you are using, as it is a memory waste to try and import everything.  You would only use **require** when importing specific functions ```const { updateJoinData, getValue,... } = require('adv-firestore-functions');``` However, you don't need **require** if you are going to use them no matter what the **IF** statement says, you can just use **import**.  I would suggest create a separate file for each function see [here](https://firebase.google.com/docs/functions/organize-functions).

3.) I am not sure what your **increment** code does, but I literally just wrote a new function **conditionQuery** so you don't have to keep up with all that.

4.) You don't need try / catch as I already have error handling in my functions.

5.) Get rid of the promises push and run the awaits one at a time.  I do not know the effects of this using my functions.  The **_events** collection will be created along with the **_counters** collection to ensure correct counting.

6.) Please read my suggestions above, it looks as if you ignored them.

6.) If you have specific problems, suggestions, or questions relating to **adv-firestore-functions**, please create a new **Issue** in this github relating to the specific problem.  If you have questions on generally how typescript or firebase functions work, please post an issue on StackOverFlow.

**Comment by prakash-indorkar** [comment]
Hi .. my apology. I had left those things for a bit later, once functions strat working. It was on my to-do list to have separate files for functions.

**Comment by prakash-indorkar** [comment]
conditionQuery is definitely a good choice to use, but in my case, isExpired happens with the date, and users are allowed to delete after item has expired. (They may not delete and it can be left in their expired list). They are also allowed to delete an item before it expires and not consumed.

 So If I calculate TotalActive count with formula 
 const totalActive = countSnap.get(count) - countSnap.get(isDeletedCount) - countSnap.get(isExpired)
 would get wrong value. 
 Thats why I'm checking for create event and incrementing activeCount.  and later depending on isExpired and isDelete event I'm updating activeCount, to avoid calculated value.
 
Maybe you are right I can avoid expiry cronjob. I was just worried if it may take a bit of time to check the records with expiry date all the time when expired item list page loads, and also making trigger call to update isExpired value especially when the list gets bigger. Hence I created cronjob.

**Comment by jdgamble555** [comment]
When the cron job searches for expired items:

```.where('bestBeforeDate', '<=', now)`` and changes **isExpired** to **true**```,

You could still use ``await conditionCounter(change, context, 'isExpired', '==', true);``` to get the updated **isExpiredCount**, as this would get triggered automatically when the cron job is ran.  This trigger will also automatically update **totalActive** from my code above automatically.

I would only update **totalActive** 
```typescript
if (valueChange(change, 'isExpired') || valueChange(change, 'isDeleted') || valueChange(change, 'isConsumed')) {
  const totalActive = countSnap.get(count) - countSnap.get(isDeletedCount) - countSnap.get(isExpiredCount);
  await countRef.set({ totalActive }, { merge: true });
}
```
**OR**

On the frontend:

```typescript
// still need conditionQueries on the backend

const isExpiredCount = [get snapshot.size of] db('your column').where('bestBeforeDate', '<=', now); // edit this
const totalActive = countSnap.get(count) - countSnap.get(isDeletedCount) - isExpiredCount;
```
Then use firestore rules to be sure an item only gets deleted when it is expired... many options here...


Both ways are legit, and you will have to manually count **isExpiredCount** not matter how you look at it.
