### ISSUE TITLE
Infinite records getting generated under _events collection

### ISSUE THREAD

**Issue by prakash-indorkar** [jdgamble555/adv-firestore-functions#11]
I went ahead and installed the firebase emulator suit to avoid future problems. Now testing functions locally.

Now this time I have removed all unnecessary code kept only 1 function to test, and again it went onto infine loop. Under logs its just generating following... and nothing else.. 
i  functions: Beginning execution of "autoCreatedAtUpdatedAt"
i  functions: Finished "autoCreatedAtUpdatedAt" in ~1s
i  functions: Beginning execution of "autoCreatedAtUpdatedAt"
i  functions: Finished "autoCreatedAtUpdatedAt" in ~1s
i  functions: Beginning execution of "autoCreatedAtUpdatedAt"
...
..

I had to quit the emulator to stop it every time. 

It created the createdAt and updatedAt fields.. But the _events collection kept on generating new documents.. 

I am 90% sure there must be some issue with the following functions using in if condition to exit
```
if (await eventExists(context) || colId.startsWith('_') || isTriggerFunction(change, context)) {
            return null;
}

Also I tested with both leading forward slash and without slash for document path - functions.firestore.document('{colId}/{docId}')

```

The testing function code looks like this
```
const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp(functions.config().firebase);
const { eventExists, isTriggerFunction, triggerFunction } = require('adv-firestore-functions');
const db = admin.firestore();
const settings = {
    timestampInSnapshots: true,
    host: "localhost:8081",
    ssl: false,
};

db.settings(settings);

exports.autoCreatedAtUpdatedAt = functions.firestore.document('{colId}/{docId}')
    .onWrite(async (change, context) => {
        const colId = context.params.colId;
        if (await eventExists(context) || colId.startsWith('_') || isTriggerFunction(change, context)) {
            return null;
        }
        await triggerFunction(change);
        return null;
    });
```

Update: 

Tested again with just one collection ---> functions.firestore.document('/users/{docId}')

this time it worked without any issues..   So I think it is somewhere considering the generated collection for the update event. To my understanding this code ----> colId.startsWith('_')  was not effective. So I can only use one collection at a time.  I tried with both single quotes and double quotes, no change.  

_events collection still generating multiple records but at least it stops ( say for just one update it creates like 15 to 20 docs)

For now, this can work for me.

I also got the following log entry, if there might be some internal issue, which I have no clue about it.

(node:11448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 log listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by jdgamble555** [comment]
You don't need ```await eventExists(context)``` in this case.  If the same function runs twice, it will simply update the **updatedAt** and **createdAt** with the latest date, no problem.  In a counter function, however, it would have the incorrect count.  I would try to stay away from universal functions in general, as they can cost you money.

**Comment by prakash-indorkar** [comment]
Sorry I did not get it .. do I need to remove just await or whole  "await eventExists(context)" function?

I tried removing "await" from eventExists(context) function .. it still goes on an infinite loop.

then I removed whole function from if condition, its working now. (But without eventExists() function colCounter() will work?). Is it possible to explain when this eventExists() is actually called so we need to check that a function shouldn't repeat?

In your example - https://fireblog.io/blog/post/firestore-counters
I see you have used, hence I used it in my code.
```
 if (await eventExists(context) || colId.startsWith('_')) {
   return null;
  }
```

Also, I have noticed one issue with conditionCounter. If an existing record gets updated its counting correct, but when a new record added with a default value (with isNice value false) .. the counter value also decreases

for example:

1 record .. isNice = false
2 record .. isNice = false

isNiceCount = 0

when I update them (one by one)
1 record .. isNice = true
2 record .. isNice = true

isNiceCount = 2

when I add a 3rd record with an initial value false

1 record .. isNice = true
2 record .. isNice = true
3 record .. isNice = false

isNiceCount = 1

**Comment by jdgamble555** [comment]
You do not need to check for events (period).  This is only necessary to prevent functions from running more than once.  If a date is updated, it does not matter, if a counter is updated, it does.

Get rid of this:

```typescript
if (await eventExists(context)
```

Keep this:
```typescript
if (colId.startsWith('_') || isTriggerFunction(change, context)) {
  return null;
}
```

You have a loop because you got rid of ```isTriggerFunction(change, context)```.  This stops the loop.

Your testing function did not have ```colCounter``` function in it.  Keep them separate.  You need the **eventExists** for that.

Create a new issue for your other problem with **conditionCounter**, meanwhile I will look at it.  Please only post one issue you have on here at a time and create a new issue for each issue.

**Comment by jdgamble555** [comment]
```npm i adv-firestore-functions@1.7.8``` and see if the **conditionCounter** problem is fixed.  Don't worry about creating a new issue.
