### ISSUE TITLE
How to implement this in firebase function

### ISSUE THREAD

**Issue by ashokv1337** [jdgamble555/adv-firestore-functions#14]
Can anyone provide a sample firebase function ready to be deployed on firebase?

**Comment by jdgamble555** [comment]
For what exactly? All you do is import the package and follow the directions depending on your needs. You need to visit Google docs for firebase function directions.

**Comment by ashokv1337** [comment]
I have done implementing in firebase
Now what it does is 
creates collection in root with _trigrams for trigramIndex and _search for releventIndex followed by provided collection name(eg. messages in my case).

for trigramIndex
final path is like => _trigrams/messages/_all/undefined

for releventIndex
final path is like => _search/messages/_all/undefined

What I think it should be like _search/messages/_all/{documentId}  i.e instead of undefined it should contain document id 

As this can be seen here, there is no parameter to set documentId it just sets automatically to undefined.

/**
 * Relevant search callable function
 * @param _opts {
 *   query - query to search
 *   col - collection to search
 *   fields - fields to search
 *   searchCol - name of search collection, default _search
 *   termField - name of term field to search, default _term
 *   filterFunc - name of function to filter
 *   limit - number of search results to limit, default 10
 *   startId - id field for paging, only works with _all index
 * }
 * @returns - will return a sorted array of docs with {id, relevance}
 *   the higher the relevance, the better match it is...
 */

while performing search it returns id as undefined.

I think we should provide a parameter or should do it automatically if possible.

Let me know if I'm doing something wrong.

**Comment by ashokv1337** [comment]
Just fixed undefined document name problem.

I have changed {docId} to {documentId} which was causing the problem

Code 

// {docId} should not change docId otherwise it will cause new document named to undefined

exports.makeSearch =  functions.firestore
    .document('/messages/{docId}')
    .onWrite(async (change, context) => {
      console.log("onWrite Change.after :"+change.after.id);
        await advance.trigramIndex(change, context, {
            fields: ['original'],
         });

        //  await advance.relevantIndex(change, context, {
        //     fields: ['original'],
        //     filterFunc: advance.soundex
        //  });

});

**Comment by jdgamble555** [comment]
Ok, I will look into whether it should be **documentId** or **docId** this evening.  

You don't necessarily need both **relevantIndex** and **trigramIndex**, as they are two different searches.

But yes, for that, basic usage:

```typescript
import { relevantIndex } from 'adv-firestore-functions';
...
await relevantIndex(change, context, {
    fields: ['original']
});
```

**Comment by jdgamble555** [comment]
It seems that it should be **docId** for both **relevant Index** and **trigram Index**:

https://github.com/jdgamble555/adv-firestore-functions/blob/master/src/shared/search.ts#L399
https://github.com/jdgamble555/adv-firestore-functions/blob/master/src/shared/search.ts#L511

I already stated this in at the top of my documentation: https://github.com/jdgamble555/adv-firestore-functions

So your code would be:

```typescript
functions.firestore
    .document('YOUR COLLECTION HERE/{docId}')
    .onWrite(async (change: any, context: any) => {
//... code

  await relevantIndex(change, context, {
     fields: ['content', 'summary']
  });

}
```
**OR**
```typescript
functions.firestore
    .document('YOUR COLLECTION HERE/{docId}')
    .onWrite(async (change: any, context: any) => {
//... code

  await trigramIndex(change, context, {
     fields: ['content', 'summary']
  });

}
```

All of this in the in the docs already.

J
