### ISSUE TITLE
Filter on tags AND-ed together.

### ISSUE THREAD

**Issue by wu-victor** [jdgamble555/adv-firestore-functions#16]
Thanks for putting this together. I came here looking for Algolia alternatives. 

I need to index and search on documents that have meta data. It is equivalent to attaching to each blog post (in a blogging app) with any number of custom tags. The user can then search on blog posts, filtering on these tags (AND-ed together). 

Is this something this library can already do?

**Comment by jdgamble555** [comment]
If you want a tag index, you can use my tag index function:

https://github.com/jdgamble555/adv-firestore-functions/blob/master/README.md#helper-functions

Scroll down to tags.  With the index, you can filter tags with where clauses.  

If you want to search the posts on top of that, use one of my search indexes:

https://fireblog.io/blog/post/which-full-text-search-index-do-i-use

J
