### ISSUE TITLE
relevantSearch is not working

### ISSUE THREAD

**Issue by RazaShehryar** [jdgamble555/adv-firestore-functions#21]

**Comment by jdgamble555** [comment]
Can you please give more context?

**Comment by RazaShehryar** [comment]
> Can you please give more context?

sorry, the issue was resolved. I am using the trigram search now. However, how do I index predefined documents? Do I need to run a callable function that gets all the documents and then create a trigram index on them?

**Comment by jdgamble555** [comment]
Yes, unfortunately you have to write something to do that manually.

J

**Comment by RazaShehryar** [comment]
is there a way to filter out the search for a particular event? For example, I have a number of guests attending an event and I only want to search for those particular guests. Is that something possible with this?

**Comment by jdgamble555** [comment]
If you have a filter.  You need a new index.  You could create an extra index by using `searchCol` to select it.

```typescript
/**
 * indexes a collection by relevance
 * @param change
 * @param context
 * @param _opts: {
 *   fields - array of fields to index
 *   searchCol - name of search collection, default _search
 *   numWords - number of words to index at a time, default 6
 *   combine - whether or not to combine fields in one collection, default true
 *   allCol - name of all fields collection, default _all
 *   termField - name of terms array, default _term
 *   filterFunc - function to filter, can pass a soundex function
 * }
 */
```
Honestly, I just would not use firebase if you need complex filters, joins, or search.  I don't use it anymore, it is no longer progressing with features.

J
