### ISSUE TITLE
Global counter for aggregated document array lenghts 

### ISSUE THREAD

**Issue by appfr3d** [jdgamble555/adv-firestore-functions#25]
Hello, I managed to use this module successfully to count the number of documents in my collections. However I wanted to have a global count for the number of items stored in arrays on each document in and collection as well and I am not sure how to do that. 

A generalization of my firestore structure is as follows: I have a user-collection, and each of the user-documents has an array containing a certain number of items. I want a global counter of how many items are stored in total in my firestore database. 

From what I can tall, neither `colCounter`, `queryCounter` nor `conditionCounter` solves my problem. Is there a way to create the counter that I want using your module?

**Comment by jdgamble555** [comment]
You would have to write your own version.  I did not write a way to count arrays like that.  

Good luck!

J
