### ISSUE TITLE
Deployment error: On trying to upload the example with minor tweak.

### ISSUE THREAD

**Issue by lateeph1** [jdgamble555/adv-firestore-functions#6]
While I try to upload the file, I get a deployment error

Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /srv/node_modules/@google-cloud/firestore/build/src/collection-group.js:54
    async *getPartitions(desiredPartitionCount) {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/@google-cloud/firestore/build/src/index.js:39:28)

```
import * as functions from 'firebase-functions';
import { eventExists, fullTextIndex } from 'adv-firestore-functions';

exports.myFunction = functions.firestore
  .document('ads/{docId}')
  .onWrite(async (change: any, context: any): Promise<any> => {

    // don't run if repeated function
    if(await eventExists(context)) {
        return null;
    }
    // index the ad
    const searchable = ['name'];
    searchable.forEach(async (field: string) => {
      await fullTextIndex(change, context, field);
    });

    return null;

  });
```

I have the following dependencies

```
"adv-firestore-functions": "^1.7.4",
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1"
```

I have deployed other functions using the same configuration with success, But I haven't have any luck with this particular function. Thanks for looking into it

**Comment by jdgamble555** [comment]
This is not my package problem, but google.  I cannot downgrade or I will looks the "where !=" feature.

1. Try reinstalling [@google-cloud/firestore](https://www.npmjs.com/package/@google-cloud/firestore#supported-nodejs-versions).
2. Make sure you have [node 10](https://firebase.google.com/docs/functions/manage-functions) or above running in your functions. Version 8 is no longer supported.
3. Run ```npm update``` in your functions directory.
4. Run ```npm install -g firebase-tools``` to update your interface.
5. All else fails, manually delete the "*" symbol in "./node_modules/@google-cloud/firestore/build/src/collection-group.js" in front of ```async *getPartitions(```

Let me know if this works.

**Comment by lateeph1** [comment]
Thanks for the pointer, I am running node 8, I'll try to switch to node 12 and see if the problem persist.
