### ISSUE TITLE
Fuzzy Search?

### ISSUE THREAD

**Issue by stevebrowndotco** [jdgamble555/adv-firestore-functions#9]
Hello,

Great work. Have you considered fuzzy search? So let's say for example I make a text index like so:

```typescript
const searchable = ['name'];
searchable.forEach(async (field) => {
  await fullTextIndex(change, context, field, 'id', 'array');
})
```
This will allow me to perform a text search like so:

```typescript
const performSearch = (term) => {
  const col = `_search/collection/type`;
  firestore.collection(col).where('_terms', 'array-contains', term).get().then(snapshot => {
    snapshot.forEach((resp)=>{
      console.log(resp.data());
    })
  });
}

performSearch('The Who');

```

"The who" will give me my result, but "Who The" will not. This is a big limitation because the user might know only some of the words not in the right order.

Thank you

**Comment by stevebrowndotco** [comment]
A bit like this: https://medium.com/@ken11zer01/firebase-firestore-text-search-and-pagination-91a0df8131ef

**Comment by jdgamble555** [comment]
This search **does** actually already do this out-of-the box.  Your example would be stored in the database as "_search/your_table/the who" as well as "_search/your_table/who", so it would work exactly the same way as your example.  

Note that is is not technically "fuzzy search," as that would be finding "coat" for "cot," etc... I have some ideas on how to implement that as well and may write code for that eventually.
